# Generated by Django 5.2.2 on 2025-07-26 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_course_management_access', models.BooleanField(default=False)),
                ('has_batch_management_access', models.BooleanField(default=False)),
                ('has_content_management_access', models.BooleanField(default=False)),
                ('has_announcement_management_access', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
